name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          npm install -D yarn
          ./node_modules/yarn/bin/yarn
          
      - name: Deploy hexo
        run: |
          hexo clean
          hexo generate --silent
          cd public/
          git init
          git add -A
          git commit -m 'deploy' --quiet
          git push -f https://${access_token}@github.com/wangxiuwen/wangxiuwen.github.io.git master:gh-pages
