name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: echo files
        run: |
          ls -alh
