name: CI

on:
  push:
    branches: [ master ]

env:
  GIT_USER: wangxiuwen
  GIT_EMAIL: wangxiuwen@wangxiuwen.com
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.19.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
      - uses: snickerbockers/submodules-init@v4

      - name: Configuration git
        run: |
          git config --global user.name ${GIT_USER}
          git config --global user.email ${GIT_EMAIL}

      - name: Install dependencies
        run: |
          npm install -D yarn
          ./node_modules/yarn/bin/yarn

      - name: Deploy hexo
        run: |
          ./node_modules/hexo/bin/hexo clean
          ./node_modules/hexo/bin/hexo generate --silent
          cd public/
          git init
          git add -A
          git commit -m 'deploy' --quiet
          git push -f https://${ACCESS_TOKEN}@github.com/wangxiuwen/wangxiuwen.github.io.git master:gh-pages
